export const actionTypes = {
  UPDATE_LANGUAGE: 'UPDATE_LANGUAGE',
  OPEN_SNACKBAR: 'OPEN_SNACKBAR',
  SNACKBAR_TEXT: 'SNACKBAR_TEXT',
  SNACKBAR_SEVERITY: 'SNACKBAR_SEVERITY',
  ADD_TO_ORDER: 'ADD_TO_ORDER',
  SET_TRANSLATED: 'SET_TRANSLATED',
  SET_PREPARED: 'SET_PREPARED',
}